### ISSUE TITLE
Contribute salary and or pay rate to survey

### ISSUE THREAD

**Issue by wstocker** [drnikki/diversity-of-the-web#4]
Optional field to contribute filling out salary and/or pay rate to survey.

**Comment by wstocker** [comment]
Maybe if added can do this as a range.

**Comment by nstielau** [comment]
My opinion is that we should stay away from salary.  It's clearly an important issue for diversity (maybe ultimately _the_ issue), but I'm hesitant to include it because I'm not sure it would yield valuable insights without enough data about location/field/experience to provide accurate analysis.  I also don't want to steal the focus from other goals, as people might gravitate to looking at salary to see how they compare.

@imtiffanyyu @drnikki what do you think?

**Comment by nstielau** [comment]
Ping @drnikki

**Comment by drnikko** [comment]
@nstielau I'd like to leave this open while we work on the rest of the survey. We can always add it or delete it at the end, and I don't feel like we have enough consensus/input into the survey at large to make this decision yet.

**Comment by nstielau** [comment]
Yeah, looking at the "big 8", it does include "Socio-Economic Status/Class".  We might be able to get that and this with a broad "family income level" question

**Comment by nstielau** [comment]
We're going to move forward without salary info.
