### ISSUE TITLE
Promotion frequency and opportunity

### ISSUE THREAD

**Issue by wstocker** [drnikki/diversity-of-the-web#5]
How often does the individual receive promotions, raises, title changes, etc within an organization.

**Comment by nstielau** [comment]
Good one.  I like it because it stays away from the "How much do you make" which seems like a can of worms for a few reasons, but does get to the point.  Not sure quite how to phrase the question, maybe "I feel raises, promotions, title changes are inconsistently applied across the organization" Strongly disagree => Strongly agree.  Might have to find some example questions.

**Comment by nstielau** [comment]
Thinking about this more, this is different than identification based questions, i.e. it is more about measuring bias than make-up.  Not sure what to do with it right now, just noting that.

**Comment by nstielau** [comment]
I.e. this is more of an 'equality' question than a 'diversity' question

**Comment by nstielau** [comment]
Going to close this out, but thanks for the suggestion.  @drnikki is going to publish a blog post about the difference between equality and diversity to highlight some of the discussion we had around topics like this.  Also, we're going to include a couple of high-level questions about the lived-experience of people in diverse work experiences.
